### ISSUE TITLE
Calling set state in a screen at a lower level will remove the displayed screen

### ISSUE THREAD

**Issue by robmr88** [n0vah/nested_navigators#10]
Hi, I am using this to create nested navigation with bottom tabs. If I call setState in the screen at level 0 while displaying a screen above it then the above screen will be popped . Could you help me to avoid this ?

**Comment by robmr88** [comment]
never mind, solved it

**Comment by buraktabn** [comment]
How did you manage to solve the issue?

**Comment by robmr88** [comment]
I went around the issue, stopped calling setState in a screen that is not visible. I couldn't actually fix it
