### ISSUE TITLE
Please update to give compatibilty with flutter 1.17

### ISSUE THREAD

**Issue by robmr88** [n0vah/nested_navigators#14]
Hi, I am using this library in a project and I would love to be able to update my project to 1.17 but initialRoute is removed in the new Flutter update. Could you please update it and make it compatible?
Thank you

**Comment by Mohammad-Adam** [comment]
+1

**Comment by buidan** [comment]
+1

**Comment by n0vah** [comment]
Fixed in version 1.0.9
