### ISSUE TITLE
Option for the hide Bottom Navigation Bar in selected Routes

### ISSUE THREAD

**Issue by buraktabn** [n0vah/nested_navigators#15]
I'm using this great library to manage routes in Bottom Navigation. However, my first page is Login Page which doesn't require a Bottom Navigation. 

So, I'd like to hide it for the Login Page. I could create an empty page and navigate directly to my Login Page with the parameter of `hideNavTabBar: true`. But, I don't think it would be the right solution.

Any suggestions?

**Comment by n0vah** [comment]
I'll do something like this. But I will also create some SplashPage (root page), where I'll check the authorization status, and then open LoginPage or MainPage.

```dart
class App extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _AppState();
}

class _AppState extends State<App> {
  final NestedNavigatorsBloc _bloc = NestedNavigatorsBloc<NestedNavItemKey>();

  @override
  Widget build(BuildContext context) {
    return NestedNavigatorsBlocProvider(
      bloc: _bloc,
      child: MaterialApp(
        title: 'Flutter Demo',
        home: LoginPage(),
        onGenerateRoute: (routeSettings) => routeSettings.name == "/main"
            ? MaterialPageRoute(settings: routeSettings, builder: (context) => MainPage())
            : Routes.generateRoute(routeSettings),
      ),
    );
  }
}

class LoginPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.white,
        alignment: Alignment.center,
        child: FlatButton(
          child: Text(
            "Login",
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 26, color: Colors.red),
          ),
          onPressed: () {
            Navigator.popAndPushNamed(context, '/main');
          },
        ),
      ),
    );
  }
}
```

**Comment by buraktabn** [comment]
Thanks for the answer.

I found an another solution for this issue. The `NestedNavigators` declared in RootPage. Therefore, it has the Bottom Navigation. So, If I set the `initialRoute` to my LoginPage it seems working well.
